---
- name: Playbook test to create gce instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
     service_account_email: [Google Cloud service_account_email]
     credentials_file: [Google json credentials_file]
     project_id: [Google project_id]
     machine_type: n1-standard-1
     image: centos-7

  tasks:
    - name: Launch instances
      gce:
        instance_names: ansi_wbs1
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
